### ISSUE TITLE
watcher dont working

### ISSUE THREAD

**Issue by lvlyRyuzaki** [xperimental/autoocr#4]
When I add a new pdf to the folder the pdf wont processed, but if I restart the docker container, the pdf get processed.

**Comment by xperimental** [comment]
@lvlyRyuzaki Thanks for the question. Without any information about how your configuration looks like I can not give you any help though.

**Comment by lvlyRyuzaki** [comment]
thank you for the fast reply

I ran the container with the following command
`docker run --name autoocr -v C:\DMS\Input:/data/input -v C:\DMS\Output:/data/output xperimental/autoocr:latest --keep-original=false`

and here are the logs 
![grafik](https://github.com/user-attachments/assets/1e7be520-babe-44b7-ad12-251a653f9925)

the processed pdf is the a pdf that was in the directory before I started the container
after the pdf is processed and added two new pdfs in the folder, but these dont get processed

let me know if you need to know someting else
![grafik](https://github.com/user-attachments/assets/75dfcff6-a397-484f-aea5-d8dbd4d7cf11)

**Comment by xperimental** [comment]
While the `fsnotify` library claims cross-platform support, I don't think it will work when running a Linux Docker image in Windows. I'm assuming that's why it does not work for you.
It would probably work when directly running the Go application in Windows, but this does not really help you, because the other tools used for processing are all Linux-based.
